### ISSUE TITLE
[问题] 请问 PyQt 的 `setStyleSheet` 具体怎么寻找 qss 文件中的文件

### ISSUE THREAD

**Issue by qin-yu** [PyQt5/PyQt#188]
你好，我在使用 `setStyleSheet()` 方程时发现某些包对路径的改动导致该方程在寻找 `.qss` 文件中描述的文件时找错地方，但我发现 PyQt 好像不是开源的代码所以也没找到这个到底怎么修复。

比如：这个文件中第145行的 style https://github.com/napari/napari/blob/6c8245ad963095ae6c528fc7f5964f393e37606a/napari/_qt/qt_resources/styles/00_base.qss#L145

```css
QComboBox::down-arrow {
   image: url("theme_{{ id }}:/drop_down_50.svg");
   width: 14px;
   height: 14px;
}
```

（其实最终形态是 `url("theme_dark:/drop_down_50.svg")`）

这个 svg 文件 `url("theme_dark:/drop_down_50.svg")` 具体是怎么被 PyQt 找到的有什么说法吗？哪里可以阅读相关资料？

谢谢！
